version: "3.9"
services:
  prometheus:
    image: "prom/prometheus:latest"
    ports:
      - "9090:9090"
    volumes:
      - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"

  tensorflow:
    image: "ia_example:latest"
    ports:
      - "8501:8501"
    entrypoint: "/usr/bin/tf_serving_entrypoint.sh"
  web:
    image: "ia_example:latest"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TENSORFLOW_HOST: tensorflow
      API_ARGS: --reload
    entrypoint: "python3 main.py"
    ports:
      - "8000:8000"
    volumes:
      - "./src/:/code/"
      - "./api_entrypoint.sh:/usr/bin/api_entrypoint.sh"
    user: "1000:1000"
    depends_on:
      - tensorflow
